interagent/prmd

- lib/prmd/templates/schemata.md.erb
- lib/prmd/templates/schemata/link.md.erb
- lib/prmd/templates/schemata/link_curl_example.md.erb
* Headers beginning with #s should have blank lines both
before and after; add this spacing.
* Add blank lines around tables (for the same reason);
this closes #189.
* Remove spurious blank line at the ends of curl examples.
* I noticed there are sometimes two blank lines *before* a
heading; this looks like it may be down to the way the
templates are coded (I'm a ruby newbie). I think it is
not a showstopper (and this patch does not affect it).
> Ensure there are spaces after headers and tables

- lib/prmd/templates/schemata/helper.erb
Hello. I would like to define object's properties in another file and $ref them in controller's schema but i can't.
Example of schema:
```json
{
"id": "schemata/api:v2:global_surveys_controller",
"type": "object",
"title": "/api/v2/global_surveys",
"description": "Global surveys controller",
"properties": {
"$ref": "/api:v2:global_survey#/definitions/properties"
},
"links": [ ]
}
```
`prmd doc` fails with `/home/predator/.rvm/gems/ruby-2.1.4@crowd/bundler/gems/prmd-a65e6fbdd4b0/lib/prmd/templates/schemata/helper.erb:111:in `build_attribute': undefined method `include?' for nil:NilClass (NoMethodError)`
> Dereference properties

- README.md
JSON doesn't support comments so it looks like this:
https://www.dropbox.com/s/1ko4hggwlyo7gro/Screenshot%202015-04-29%2012.25.16.png?dl=0
This change makes it easier to read.
> Update README snippet from JSON to JS

- lib/prmd/templates/schemata/helper.erb
We forgot to turn them into their JSON representation as well as to mark
them as code in markdown.
> render default examples correctly

- lib/prmd/templates/schemata.md.erb
- lib/prmd/templates/schemata/helper.erb
When a resource's property refers to another resource, create links in
the first resource's attributes list to the second resource.
When a property is a nullable object consisting of properties from other
resources, and if all the properties refer to the same resource, the
nullable object's entry will also link to that resource, even if the
nullable object wasn't a direct reference.
Attached are several examples, generated from Heroku's schema. The last example, for `Organization App` demonstrates what happens when a schema reuses most attributes of another schema. We don't just linkify embedded objects, but all attributes that are defined in another schema. This makes the code simpler and the behaviour more predictable.
Closes #217
> Link to resources from attributes list

- lib/prmd/templates/schemata/link.md.erb
This avoids emitting an empty `<pre></pre>` when there's no response example. I'm not sure if the empty `pre` was a deliberate decision (then just ignore my patch) or if it was an oversight. It certainly looks funny when `pre` is styled to stand out.
> don't emit empty pre block when there's no response example

- test/commands/verify_test.rb
Update `test_resource_link_href_format` test to use invalid character in order to fix broken master.
```
1) Failure:
InteragentHyperSchemaVerifyTest#test_resource_link_href_format [/home/travis/build/interagent/prmd/test/commands/verify_test.rb:113]:
Expected: 1
Actual: 0
51 runs, 133 assertions, 1 failures, 0 errors, 0 skips
rake aborted!
Command failed with status (1): [ruby -I"lib" -I"/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib" "/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/rake-10.4.2/lib/rake/rake_test_loader.rb" "test/**/*_test.rb" ]
/home/travis/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
/home/travis/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => default => test
(See full trace by running task with --trace)
```
> fix test_resource_link_href_format test

- lib/prmd/cli.rb
- lib/prmd/cli/stub.rb
borrowing from the idea of committee-stub
Note, will probably need/want to provide ways to pass in additional config (ie stuff like tolerant mode from committee stub, which doesn't do request/response validation), but this is at least a good start.
Also note that presently you would need to add committee to installed/bundled stuff on your own, to avoid adding it to the gem deps for those that don't need it (though perhaps just adding it isn't too off-base).
> first pass at adding stub command

- lib/prmd/schema.rb
- lib/prmd/templates/schemata/helper.erb
Given this example schema:
```
grant_type:
description: "Authentication method to use."
type: "string"
enum: ["password", "auth_code"]
```
It is obvious that e.g. `password` is a valid value for `grant_type` and can therefore be used as a default example if no `example` key is specified.
Two questions:
* The current default example for strings is displayed as `"password"`. This change however displays them just as `password`. I wasn't quite sure how/where to handle this. `schema_value_example` is the wrong place since that is also used in the CURL example
* The changed `elsif`  in `build_attribute` looks quite ugly now, but I did not want to duplicate the call to `schema_value_example`. Also, I'm not sure that condition actually covers all scenarios where we would want to get the example …
> Add default example for enum type

- lib/prmd/cli/generate.rb
- lib/prmd/commands/init.rb
This modifies the init command to allow users to specify their own init template. We are using json-api so there are a lot of differences between the included PRMD resource template and what we want. If no template is provided it will default to the PRMD template as before.
> Allow custom init template to be used

- lib/prmd/rake_tasks/doc.rb
`NameError: uninitialized constant Prmd::Link` was thrown before when generating
documentation via the included Rake task. Requiring `prmd/link` seems to solve
the issue.
This pull request solves the issue mentioned in https://github.com/interagent/prmd/issues/263.
The build is failing, but it appears to be unrelated to this pull request.
CC: @geemus.
> Fix `NameError` when generating documentation via Rake task.

- lib/prmd/cli/verify.rb
- lib/prmd/commands/verify.rb
Hi!
For our particular use of prmd we have a custom hyper schema to describe our schema. We've previously forked and modified the `SCHEMAS` constant in `lib/prmd/commands/verify` to add this schema, but it would be nice to be able to pass it in as a command line argument.
This is a draft of what that implementation might look like. Is this something you'd consider adding?
> Add option to pass a custom hyper schema to Verify

- .travis.yml
Latest builds on travis are broken because of bundler is too old and contains some issues.
Refs: [bundler/bundler#3558](https://github.com/bundler/bundler/issues/3558) [travis-ci/travis-ci#3531](https://github.com/travis-ci/travis-ci/issues/3531)
> Specify install bundler version in travis builds

- lib/prmd/commands/combine.rb
- test/commands/combine_test.rb
Automatically escapes '#' and '/' when they appear inside of '{()}' of an 'href'
definition.
Addresses #106, using the code snippet provided by @ilovenwd.
I was a bit unsure where to put `self.escape_hrefs`. If you think there's a better place for it, I'm happy to move it somewhere else. Also, I opted for testing the private method directly to avoid setting up files etc. and making it a bit easier to stub various hrefs. If you'd like to test all of `self.combine` instead, let me know and I'll change it.
> Escape references in href to make it more readable

- lib/prmd/commands/combine.rb
Otherwise only the tests pass, but combining fails because dereferencing is
errors on lib/prmd/schema.rb:90: undefined method `gsub' for nil:NilClass.
Sorry for screwing this up, should have tested the updated version with actual code. The tests lied because there `data` is a `Hash` ...
> Escape if data is a SchemaHash too

- lib/prmd/rake_tasks/combine.rb
- lib/prmd/rake_tasks/doc.rb
- lib/prmd/rake_tasks/verify.rb
`Rake::Application#last_comment` was deprecated and removed in v11.
> Use `Rake::Application#last_description`

- lib/prmd/cli/combine.rb
- lib/prmd/commands/combine.rb
- lib/prmd/core/combiner.rb
- lib/prmd/schema.rb
The json schema library I am using to parse looks for strings rather than arrays for types.  I don't plan on using multiple types as an array so I added a flag to allow type as string.
ex: prmd combine --meta meta.json --type-as-string schemata/ > schema.json
> Command line flag to allow types as strings rather than arrays

- docs/schemata.md
- lib/prmd/schema.rb
json_schema supports it, so prmd did not fail when I used `date` as a format,
but the generated example was empty.
See
https://github.com/brandur/json_schema/blob/v0.13.0/lib/json_schema/validator.rb#L543.
> Add example when using date format

- lib/prmd/schema.rb
won't convert `"type": "xxx"` to `"type": ["xxx"]` in `"example"`
sometimes I write an example as an object, if it has "type" key in anywhere, it will be changed to an array by `convert_type_to_array`.
It's really unnecessary to modify "example" in schema, I skipped it.
Why do I write object in example? because prmd won't generate examples for "patternProperties"
I have an another question, what is the propose of `convert_type_to_array`?
> don't convert type to array in example

- lib/prmd/rake_tasks/doc.rb
- lib/prmd/templates/schema.erb
- lib/prmd/templates/table_of_contents.erb
When we use very large JSON Schema, the document will be very large too.
The prmd output the doc as one markdown file and very large markdown file is difficult to understand.
This PR add table of contents option.
When toc option enable, insert toc into the top of markdown file.
```
- <a href="#resource-user">User</a>
- <a href="#resource-post">Post</a>
.....
```
I will write the document.
> [WIP] 🎉 add table of contents

- lib/prmd/templates/schemata/helper.erb
Fixes problem of &#124; being outputted because it's wrapped in a code block.
> Stop replacing pipe char with encoded

- lib/prmd/templates/schema.erb
- lib/prmd/templates/table_of_contents.erb
- test/commands/render_test.rb
In link anchor at TOC, Decode HTML meta characters using `build_link_path` helper.
and, change TOC header from `<h1>` to `<h2>`
> fix encoded link anchor at TOC

- lib/prmd/rake_tasks/doc.rb
When options[:settings] is provided by schema:doc block on Rakefile, but not import json file.
Used: `settings.json`
```json
{
"doc": {
"toc": true
}
}
```
I add a testing code into `template/schema.rb` on line 1 (before apply this pull request)
```ruby
<%- puts options[:doc].inspect %>
```
results.
```
{:url_style=>"default", :disable_title_and_description=>false, :toc=>false}
```
So I copy settings json loading script from cli/doc.rb to rake_tasks/doc.rb . (I think, it might bad coding)
after merge this request.
```
{:url_style=>"default", :disable_title_and_description=>false, :toc=>true}
```
If my modification is bad, instead fix sample Raketask (this is example and no testing)
```
Prmd::RakeTasks::Doc.new do |t|
settings = Prmd.load_schema_file("docs/settings.json") …
```
> Import options from settings on RakeTask::Doc

- lib/prmd/schema.rb
Enable `allOf` Example.
Before:
```
rake aborted!
NoMethodError: undefined method `[]' for nil:NilClass
/Users/shota/Docs/api.umee.be/vendor/bundle/ruby/2.4.0/gems/prmd-0.13.0/lib/prmd/schema.rb:138:in `schema_value_example'
```
in 138:
```ruby
def schema_value_example(value)
if value.key?('example')
value['example']
elsif value.key?('anyOf')
id_ref = value['anyOf'].find do |ref|
ref['$ref'] && ref['$ref'].split('/').last == 'id'
end
ref = id_ref || value['anyOf'].first
schema_example(ref)
elsif value.key?('properties') # nested properties
schema_example(value)
elsif value.key?('items') # array of objects
_, items = dereference(value['items'])
if value['items'].key?('example')
if items["example"].is_a?(Array)
items["example"]
else
[items['example']]
end
else
[schema_example(items)]
end …
```
> Support allOf example (testing)

- lib/prmd/templates/schemata/helper.erb
When I use union type for some reason (for example, big int support), prmd documents show only first type only.
```
properties:
id:
description: "ID"
type:
- string
- number
```
I want prmd to display all types.
> Show union type

- lib/prmd/templates/schemata.md.erb
By the PR (https://github.com/interagent/prmd/pull/330), we need opening details to use table of contents links now.
I guess here is a better position.
I changed
From,
```
Details >
- Attributes (don't show when there are no properties)
- Links
- Details >
```
To,
```
- Attributes (don't show when there are no properties)
- Details >
- Links
- Details >
```
> Move details tags

- lib/prmd/templates/schemata/helper.erb
- test/commands/render_test.rb
This fixes a bug observed with the Heroku Platform API schema markdown, which is that when it puts a "pattern" in a table like this, the pipe gets interpreted as part of the markdown table, even though it is inside a code block. The solution for this is to render the pattern part in a `<pre></pre>` tag with an htmlentity for the pipe.
Here's what the bug looks like:
```markdown
| **deploy_target:id** | *string* | unique identifier of deploy target<br/> **pattern:** `(^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$|^[a-z]{2}$)` | `"us"` |
| **deploy_target:type** | *string* | type of deploy target<br/> **pattern:** `(^space$|^region$)` | `"region"` |
```
becomes:
> Escape patterns (regexes) in markdown

- lib/prmd/templates/schemata/helper.erb
- test/commands/render_test.rb
In https://github.com/interagent/prmd/pull/345/ a bug was fixed where a regexp containing a pipe character would close the table cell it was in. Because the fix uses `<pre>` instead of the backticks notation for inline code in markdown, the content of the `<pre>` element was being parsed as markdown.
It is not unusual for a regexp to contain what looks like a markdown link (`[...](...)`) so that introduced a new bug.
I believe this PR will fix that bug, while introducing a new test case for them
> ensure regexp in tables is rendered correctly
